#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aoscloud
      url-base: https://github.com/aoscloud

    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: xen-troops
      revision: b1ab92967739d06599231d0ee4f4c8d68a6681b0
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aoscloud
      revision: v0.2.1

    - name: aos_core_api
      remote: aoscloud
      revision: v7.2.1

    - name: zephyr-xenlib
      remote: xen-troops
      revision: ecc874c0b667f9080fb210e1acca25eab4500f6f

    - name: littlefs
      remote: zephyrproject-rtos
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
      path: modules/fs/littlefs
      groups:
        - fs

    - name: nanopb
      remote: zephyrproject-rtos
      revision: 42fa8b211e946b90b9d968523fce7b1cfe27617e
      path: modules/lib/nanopb

    - name: tinycrypt
      remote: zephyrproject-rtos
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto

    - name: zephyr-optee-client
      remote: xen-troops
      revision: 9e8e574639672d34b6452741b43537cb4b03eb90
