#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aosedge
      url-base: https://github.com/aosedge

    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: xen-troops
      revision: "7e955b05a6c0f0d26032cb025de9e17649f90b12"
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aosedge
      revision: "v0.3.3"

    - name: aos_core_api
      remote: aosedge
      revision: "v7.3.3"

    - name: zephyr-xenlib
      remote: xen-troops
      revision: "86191241ec6b3ee92d96c3c110c520f25a8a6251"

    - name: zephyr-optee-client
      remote: xen-troops
      revision: "master"

    - name: nanopb
      remote: zephyrproject-rtos
      revision: "65cbefb4695bc7af1cb733ced99618afb3586b20"
      path: modules/lib/nanopb

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: "3217c450180fd5e817601c6f479116de69e57461"
      path: modules/crypto/mbedtls
      groups:
        - crypto

    - name: fatfs
      remote: zephyrproject-rtos
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
