#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aosedge
      url-base: https://github.com/aosedge

    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: xen-troops
      revision: zephyr-v3.6.0-xt
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aosedge
      revision: "feature_dynamic_nodes"

    - name: aos_core_api
      remote: aosedge
      revision: "feature_dynamic_nodes"

    - name: zephyr-xenlib
      remote: xen-troops
      revision: "main"

    - name: zephyr-optee-client
      remote: xen-troops
      revision: "soafee_1.1_wip"

    - name: zephyr-xrun
      remote: xen-troops
      revision: "main"

    - name: littlefs
      remote: zephyrproject-rtos
      revision: "zephyr"
      path: modules/fs/littlefs
      groups:
        - fs

    - name: nanopb
      remote: zephyrproject-rtos
      revision: "zephyr"
      path: modules/lib/nanopb

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: "zephyr"
      path: modules/crypto/mbedtls
      groups:
        - crypto
